export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_RECIPE = "ADD_RECIPE";
export const GET_RECIPES = "GET_RECIPES";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const RECIPES_LOADING = "RECIPES_LOADING";
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
